source 'https://rubygems.org'
gem 'rspec'
gem 'cucumber'
gem 'json'
gem 'sinatra'
gem 'haml'
gem 'rake'                                                                                                                                              
